Eldritch input parameters from JSON.
KCarretto/realm pull request #121
Opened 2023-02-28 05:44 UTC by hulto

#### What type of PR is this?
/kind feature
/kind eldritch-function

#### What this PR does / why we need it:
Add support for parameters in eldritch.
- Allows tomes to be reusable
- Tome inputs can be string, number, or list of strings.

#### Which issue(s) this PR fixes:
Fixes #119

2023-02-28 23:50 UTC, Cictrone requested changes
kyle and nick in the mooooooooooorning

2023-02-28 23:50 UTC, Cictrone commented on implants/eldritch/src/lib.rs
> +    let obj: serde_json::Map<String, serde_json::Value> = parsed.as_object().unwrap().clone();
unwrap = nick sadge

2023-02-28 23:50 UTC, Cictrone commented on implants/eldritch/src/lib.rs
> +    let obj: serde_json::Map<String, serde_json::Value> = parsed.as_object().unwrap().clone();
nit: name var something like param_map

2023-02-28 23:50 UTC, Cictrone commented on implants/eldritch/src/lib.rs
> +            new_value = module.heap().alloc_str(value.as_str().unwrap()).to_value();
unwrap

2023-02-28 23:50 UTC, Cictrone commented on implants/eldritch/src/lib.rs
> +            for sub_value in value.as_array().unwrap() {
unwrap

2023-02-28 23:50 UTC, Cictrone commented on implants/eldritch/src/lib.rs
> +                    tmp_list.push(module.heap().alloc_str(sub_value.as_str().unwrap()).to_value());
unwrap

2023-02-28 23:50 UTC, Cictrone commented on implants/eldritch/src/lib.rs
> +        input_vars.insert_hashed(new_key.to_value().get_hashed().unwrap(), new_value);
unwrap

2023-02-28 23:50 UTC, Cictrone commented on implants/eldritch/src/lib.rs
> +    module.set("input_vars", input_vars.alloc_value(module.heap()));
in docs/ui its called params, why not here?

2023-02-28 23:50 UTC, Cictrone commented on implants/eldritch/src/lib.rs
> +    let res_str = res.to_str();
does this panic? if so maybe should return to monke

2023-02-28 23:50 UTC, Cictrone commented on implants/imix/src/main.rs
> +        // assert_eq!(result.1, "".to_string());
delete comment

2023-02-28 23:50 UTC, Cictrone commented on implants/eldritch/src/lib.rs
> +        // println!("{:?}", test_res);
delete comment

2023-03-02 04:21 UTC, KCarretto commented on implants/imix/src/main.rs
> +        println!("{:?}", result.clone());
We sure we always want to print this?

2023-03-02 04:21 UTC, KCarretto approved these changes
Stunning. Gorgeous. Beautiful. Breathtaking.

2023-03-02 04:22 UTC, merged