Implement process.name
KCarretto/realm pull request #332
Opened 2023-10-23 23:29 UTC by adm1nPanda

modified:   docs/_docs/user-guide/eldritch.md
	modified:   implants/lib/eldritch/src/process/name_impl.rs

#### What type of PR is this?
/kind feature
/kind eldritch-function

#### What this PR does / why we need it:
Implement process.name as per #58

#### Which issue(s) this PR fixes:

Fixes #58

2023-10-24 00:03 UTC, hulto requested changes
Hey adm1nPanda,
Thank you for submitting a PR!
We're excited to have you contribute I've left a few questions and suggestions. Really great job on your first PR 🙂

2023-10-24 00:03 UTC, hulto commented on implants/lib/eldritch/src/process/name_impl.rs
> +        }
Could you add an else here to make it clear the test will fail on non-supported OSes.
```rust
else {
    return anyhow::anyhow!(Err("OS Not supported please re run on Linux, Windows, or MacOS");
}
```

2023-10-24 02:07 UTC, hulto approved these changes
Looks great! 🚀

2023-10-24 15:40 UTC, adm1nPanda commented
windows workflow failing in actions but passes in my lab. made some changes which i hope will clear this time

2023-10-25 15:08 UTC, KCarretto commented on implants/lib/eldritch/src/process/name_impl.rs
> +         Pleases see sysinfo docs for a full list of supported systems.
Nit: Please see*

2023-10-26 01:47 UTC, hulto commented
Looks good! Go ahead and sqaush and merge.

2023-10-26 01:47 UTC, hulto approved these changes

2023-10-28 15:03 UTC, merged